version: '3'

services:
  app: &app
    container_name: app
    build: .
    command: ["/bin/sh", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - LANG=C.UTF-8
      - BUNDLE_PATH=vendor/bundle
      - RAILS_ENV=development
    env_file: ./.env
    working_dir: /usr/src/app
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
  data:
    container_name: data
    image: busybox
    volumes:
      - db:/var/lib/postgresql/data:delegated

volumes:
  db:
    driver: local
