name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev dialog apt-utils
      - name: Build App
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres?encoding=utf8&pool=5&timeout=5000
        run: |
          gem install bundler
          bundle install --quiet --jobs 4 --retry 3
      - name: Prepare database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run test
        run: bin/rspec
